// Here's the corrected styles.js file with the duplicate modal styles removed

import { StyleSheet, Platform, StatusBar, Dimensions } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000000",
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  content: {
    flex: 1,
    flexDirection: "row",
  },
  menuButton: {
    position: "absolute",
    top: Platform.OS === "web" ? 20 : 15,
    left: 15,
    zIndex: 10,
    padding: 8,
  },
  sidebar: {
    width: 280,
    backgroundColor: "#111111",
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 5,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    display: "flex",
    flexDirection: "column",
  },
  sidebarHeader: {
    padding: 20,
    paddingTop: Platform.OS === "web" ? 20 : 10,
    borderBottomWidth: 1,
    borderBottomColor: "#222",
  },
  sidebarTitle: {
    color: "#6397C9",
    fontSize: 24,
    fontWeight: "bold",
  },
  sidebarContent: {
    flex: 1,
    padding: 15,
  },
  sidebarButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: "#1A1A1A",
  },
  sidebarButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    marginLeft: 12,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: "#222",
  },
  logoutButtonText: {
    color: "#6397C9",
    fontSize: 16,
    marginLeft: 12,
  },
  mainContent: {
    flex: 1,
    padding: 20,
    paddingTop: Platform.OS === "web" ? 20 : 15,
  },
  mainContentLarge: {
    marginLeft: 280,
  },
  searchContainer: {
    marginBottom: 20,
    paddingTop: Platform.OS === "web" ? 0 : 10,
    paddingHorizontal: Platform.OS === "web" ? 0 : 15,
  },
  searchWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
    borderRadius: 25,
    paddingHorizontal: 15,
    height: 40,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 16,
    height: "100%",
  },
  logBookHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingHorizontal: Platform.OS === "web" ? 0 : 15,
  },
  logBookTitle: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "bold",
  },
  addButton: {
    backgroundColor: "#6397C9",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    elevation: 3,
    shadowColor: "#6397C9",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  addButtonText: {
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 14,
  },
  logBook: {
    flex: 1,
    paddingHorizontal: Platform.OS === "web" ? 0 : 15,
  },
  logEntry: {
    backgroundColor: "#1A1A1A",
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
  },
  logText: {
    color: "#FFFFFF",
  },

  // Camera styles
  cameraContainer: {
    width: "100%",
    height: 450, // Fixed height for better proportions
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#111111",
    overflow: "hidden",
    marginBottom: 20,
    borderRadius: 8,
  },
  camera: {
    flex: 1,
    width: "100%",
  },
  cameraOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  scanFrame: {
    width: 200,
    height: 200,
    borderWidth: 2,
    borderColor: "#6397C9",
  },
  scanSuccessOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  scanSuccessText: {
    color: "#6397C9",
    fontSize: 18,
    marginTop: 10,
    textAlign: "center",
  },
  cameraText: {
    color: "#6397C9",
    fontSize: 18,
  },

  // Modal styles - improved for modern look
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  modalContent: {
    width: Platform.OS === "web" ? "40%" : "90%",
    maxWidth: 500,
    backgroundColor: "#1A1A1A",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    overflow: "hidden",
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#6397C9",
    textAlign: "center",
    marginBottom: 20,
    width: "100%",
  },
  modalInput: {
    width: "100%",
    height: 55,
    backgroundColor: "#2A2A2A",
    borderWidth: 1,
    borderColor: "#6397C9",
    borderRadius: 10,
    paddingHorizontal: 15,
    marginBottom: 20,
    fontSize: 16,
    color: "#FFFFFF",
  },
  modalButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 10,
  },
  modalButton: {
    flex: 1,
    backgroundColor: "#6397C9",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 8,
    height: 50,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cancelButton: {
    backgroundColor: "#FF4444",
  },
  modalButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
});

export default styles;
